name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm run format:check
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm run routes
      - run: npm run build
      - run: >
          docker-compose up postgres &
          WAIT_DEBUG=1 bash src/scripts/wait.sh docker-compose exec -T postgres psql postgres postgres -c '\q'
      - run: npm run db:create:test
      - run: npm run test
